version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongo
        container_name: loners-hapi-api
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_USERNAME: $MONGO_USERNAME
            MONGO_PASSWORD: $MONGO_PASSWORD
            MONGO_HOSTNAME: mongo
            MONGO_PORT: $MONGO_PORT
            MONGO_DB: $MONGO_DB
        ports:
            - 8080:3000
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        networks:
            - loners-app-network

    mongo-express:
        image: mongo-express:0.54
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        env_file: .env
        environment:
            ME_CONFIG_MONGODB_PORT: $MONGO_PORT
            ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
            ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
            ME_CONFIG_BASICAUTH_USERNAME: $MONGO_USERNAME
            ME_CONFIG_BASICAUTH_PASSWORD: $MONGO_PASSWORD
        networks:
            - loners-app-network

    mongo:
        image: mongo:4.2
        container_name: mongo
        restart: unless-stopped
        env_file: .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
            MONGO_INITDB_DATABASE: $MONGO_DB
        ports:
            - 27017:27017
        volumes:
            - dbdata:/data/db
        networks:
            - loners-app-network

networks:
    loners-app-network:
        driver: bridge
    
volumes:
    dbdata:
    node_modules: 